package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("app_util", "key_id", AppUtil.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("frag", "frag_id", Frag.class);
		arp.addMapping("group", "group_id", Group.class);
		arp.addMapping("spot", "spot_id", Spot.class);
		arp.addMapping("team_chat_record", "group_id", TeamChatRecord.class);
		arp.addMapping("user", "user_id", User.class);
		// Composite Primary Key order: user_id,user_id_2
		arp.addMapping("user_chat_record", "user_id,user_id_2", UserChatRecord.class);
		// Composite Primary Key order: spot_id,user_id
		arp.addMapping("user_spot", "spot_id,user_id", UserSpot.class);
	}
}

