package com.demo.common.model;

import com.demo.common.model.base.BaseAppUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUtil extends BaseAppUtil<AppUtil> {
	public static final AppUtil dao = new AppUtil();
}
