package com.demo.common.model;

import com.demo.common.model.base.BaseFrag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Frag extends BaseFrag<Frag> {
	public static final Frag dao = new Frag();
}
