package com.demo.common.model;

import com.demo.common.model.base.BaseSpot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Spot extends BaseSpot<Spot> {
	public static final Spot dao = new Spot();
}
