package com.demo.common.model;

import com.demo.common.model.base.BaseTeamChatRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamChatRecord extends BaseTeamChatRecord<TeamChatRecord> {
	public static final TeamChatRecord dao = new TeamChatRecord();
}
