package com.demo.common.model;

import java.util.List;
import java.util.UUID;

import com.demo.common.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<User> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from user order by user_id asc");
	}
	public List<User> getlistuser(){
		List<User>users = User.dao.find("select * from user");
		return users;
		
	}
	public String adduser(String username, String userpwd){
		User user = new User().set("user_id", UUID.randomUUID().toString()).set("user_name", username).set("user_pwd",userpwd).set("email",username);
		user.save();
		String user_id = user.getUserId();
		return user_id;
	}
	
}
