package com.demo.common.model;

import com.demo.common.model.base.BaseUserChatRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserChatRecord extends BaseUserChatRecord<UserChatRecord> {
	public static final UserChatRecord dao = new UserChatRecord();
}
