package com.demo.common.model;

import com.demo.common.model.base.BaseUserSpot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSpot extends BaseUserSpot<UserSpot> {
	public static final UserSpot dao = new UserSpot();
}
