package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserChatRecord<M extends BaseUserChatRecord<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setUserId2(java.lang.String userId2) {
		set("user_id_2", userId2);
	}

	public java.lang.String getUserId2() {
		return get("user_id_2");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
