package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFrag<M extends BaseFrag<M>> extends Model<M> implements IBean {

	public void setFragId(java.lang.String fragId) {
		set("frag_id", fragId);
	}

	public java.lang.String getFragId() {
		return get("frag_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setValue(java.lang.Integer value) {
		set("value", value);
	}

	public java.lang.Integer getValue() {
		return get("value");
	}

	public void setRarity(java.lang.Integer rarity) {
		set("rarity", rarity);
	}

	public java.lang.Integer getRarity() {
		return get("rarity");
	}

	public void setVisibleRange(java.lang.Integer visibleRange) {
		set("visible_range", visibleRange);
	}

	public java.lang.Integer getVisibleRange() {
		return get("visible_range");
	}

}
