package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserSpot<M extends BaseUserSpot<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setSpotId(java.lang.String spotId) {
		set("spot_id", spotId);
	}

	public java.lang.String getSpotId() {
		return get("spot_id");
	}

	public void setNumOfStep(java.lang.Integer numOfStep) {
		set("num_of_step", numOfStep);
	}

	public java.lang.Integer getNumOfStep() {
		return get("num_of_step");
	}

	public void setFrags(java.lang.String frags) {
		set("frags", frags);
	}

	public java.lang.String getFrags() {
		return get("frags");
	}

	public void setCompletionPersional(java.lang.Integer completionPersional) {
		set("completion_persional", completionPersional);
	}

	public java.lang.Integer getCompletionPersional() {
		return get("completion_persional");
	}

	public void setCompletionTeam(java.lang.Integer completionTeam) {
		set("completion_team", completionTeam);
	}

	public java.lang.Integer getCompletionTeam() {
		return get("completion_team");
	}

}
