package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUtil<M extends BaseAppUtil<M>> extends Model<M> implements IBean {

	public void setKeyId(java.lang.String keyId) {
		set("key_id", keyId);
	}

	public java.lang.String getKeyId() {
		return get("key_id");
	}

	public void setKeyName(java.lang.String keyName) {
		set("key_name", keyName);
	}

	public java.lang.String getKeyName() {
		return get("key_name");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
