package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSpot<M extends BaseSpot<M>> extends Model<M> implements IBean {

	public void setSpotId(java.lang.String spotId) {
		set("spot_id", spotId);
	}

	public java.lang.String getSpotId() {
		return get("spot_id");
	}

	public void setCnName(java.lang.String cnName) {
		set("cn_name", cnName);
	}

	public java.lang.String getCnName() {
		return get("cn_name");
	}

	public void setFragCoords(java.lang.String fragCoords) {
		set("frag_coords", fragCoords);
	}

	public java.lang.String getFragCoords() {
		return get("frag_coords");
	}

	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}

	public java.lang.String getImgs() {
		return get("imgs");
	}

	public void setRecommendImgs(java.lang.String recommendImgs) {
		set("recommend_imgs", recommendImgs);
	}

	public java.lang.String getRecommendImgs() {
		return get("recommend_imgs");
	}

	public void setRecommendIndex(java.lang.Integer recommendIndex) {
		set("recommend_index", recommendIndex);
	}

	public java.lang.Integer getRecommendIndex() {
		return get("recommend_index");
	}

	public void setEnName(java.lang.String enName) {
		set("en_name", enName);
	}

	public java.lang.String getEnName() {
		return get("en_name");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}

	public java.lang.String getPosition() {
		return get("position");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

}
